version: '3.9'

volumes:
  bot_template_project_local_postgres_data: {}
  bot_template_project_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: bot_template_project_local_django
    container_name: bot_template_project_local_django
    platform: linux/x86_64
    restart: on-failure
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  aiogram:
    build:
      context: .
      dockerfile: ./compose/local/aiogram/Dockerfile
    image: image: aiogram/telegram-bot-api:latest
    container_name: bot_template_project_local_aiogram
    platform: linux/x86_64
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.aiogram
    command: python ./apps/bot/aiogram_inline_keyboard_bot.py    

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bot_template_project_production_postgres
    container_name: bot_template_project_local_postgres
    restart: on-failure
    volumes:
      - bot_template_project_local_postgres_data:/var/lib/postgresql/data:Z
      - bot_template_project_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres


  redis:
    image: redis:6
    container_name: bot_template_project_local_redis
    restart: on-failure

  celeryworker:
    <<: *django
    image: bot_template_project_local_celeryworker
    container_name: bot_template_project_local_celeryworker
    restart: on-failure
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: bot_template_project_local_celerybeat
    container_name: bot_template_project_local_celerybeat
    restart: on-failure
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
